# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/team12aero

    steps:
      - checkout
      
      - add_ssh_keys:
          fingerprints:
            - "e7:f7:9a:55:6e:af:af:7e:10:a3:a4:81:66:5c:e7:ac"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-



      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
        
      - run:
          command: |
            ssh -oStrictHostKeyChecking=no circleci@team12.dev.softwareengineeringii.com
            cd team12aero
            ssh-agent bash -c 'ssh-add /home/circleci/.ssh/id_rsa_git; git pull'
            #scp -r ~/team12aero/* 'circleci@team12.dev.softwareengineeringii.com:~/.'
