# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10
      
      # Specify service dependencies here if necessary
      - image: circleci/mongo:3.6.3

    working_directory: ~/team12aero

    steps:
      - checkout
      
      - add_ssh_keys:
          fingerprints:
            - "e7:f7:9a:55:6e:af:af:7e:10:a3:a4:81:66:5c:e7:ac"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-



      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
        
      - run:
          #deploy
          command:
            - ssh -oStrictHostKeyChecking=no circleci@team12.dev.softwareengineeringii.com "./deploy_project.sh"
            #~/deploy_project.sh :
            ##change to project working directory
            #cd ~/team12aero;
            ##add id_rsa_git key file for github access, clone project repo from origin
            #ssh-agent bash -c 'ssh-add /home/circleci/.ssh/id_rsa_git; git pull'
            ##install dependencies with npm
            #npm install
            ##node test => launch process manager to bring project online
            #node app.js && pm2 restart www

            
